version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    links:
      - mariadb:db

  spring-api:
    build:
      context: .
      dockerfile: Dockerfile.spring
    container_name: spring-api
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  apache-web:
    image: httpd:latest
    container_name: apache-web
    ports:
      - "8100:80"
    volumes:
      - /frontend_angular/www:/usr/local/apache2/htdocs


